// <auto-generated />
namespace Inschrijven.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class toestemming_many_soort : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(toestemming_many_soort));
        
        string IMigrationMetadata.Id
        {
            get { return "201807021419430_toestemming_many_soort"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
