// <auto-generated />
namespace Inschrijven.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class toestemmingsoort_code_opt : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(toestemmingsoort_code_opt));
        
        string IMigrationMetadata.Id
        {
            get { return "201807021440015_toestemmingsoort_code_opt"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
